// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARWRiPPdTofmiiwghHrVtwhhad-gOYZM8',
    appId: '1:663721322640:web:99bd3d34585579f8701015',
    messagingSenderId: '663721322640',
    projectId: 'chatapp-40332',
    authDomain: 'chatapp-40332.firebaseapp.com',
    storageBucket: 'chatapp-40332.appspot.com',
    measurementId: 'G-SKB5FW4KD4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqcN4X2mJba9TOqi0367uXvwWg2_PxR-g',
    appId: '1:663721322640:android:701634119eb3fa8f701015',
    messagingSenderId: '663721322640',
    projectId: 'chatapp-40332',
    storageBucket: 'chatapp-40332.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoPmmcUpLKS8s2Mzv0Kg5qCkFrQ3GbdlM',
    appId: '1:663721322640:ios:ca730a91789f0342701015',
    messagingSenderId: '663721322640',
    projectId: 'chatapp-40332',
    storageBucket: 'chatapp-40332.appspot.com',
    iosClientId: '663721322640-2i0eib3es1ql3lk2n1j8k8na747jt9nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenNoteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoPmmcUpLKS8s2Mzv0Kg5qCkFrQ3GbdlM',
    appId: '1:663721322640:ios:ca730a91789f0342701015',
    messagingSenderId: '663721322640',
    projectId: 'chatapp-40332',
    storageBucket: 'chatapp-40332.appspot.com',
    iosClientId: '663721322640-2i0eib3es1ql3lk2n1j8k8na747jt9nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.authenNoteApp',
  );
}
